# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *' # Runs daily at 00:00 (CEST/GMT+1)

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories
          config_display: large
          config_timezone: Europe/Ljubljana
          optimize: no
          use_prebuilt_image: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
